// This file was generated by ChatGPT-4 
// Please ask Mark for the chat history if needed. 
// Modifications are encouraged, beep boops. Robots are dumb.  

#ifndef LOAD_CELL_H
#define LOAD_CELL_H

#include "Sensor.h"

class LoadCell : public Sensor {
public:
    LoadCell(int labelID, int pinID, int pinDigital, int pinPWM, std::string unit, 
             float rangeMax, float calibrationOffset = 0.0f);

    float readData() override;
    int writeData(float data) override;
};

#endif // LOAD_CELL_H
