// This file was generated by ChatGPT-4 
// Please ask Mark for the chat history if needed. 
// Modifications are encouraged, beep boops. Robots are dumb.  

#ifndef SENSOR_H
#define SENSOR_H

#include <string>

// Sensor class definition
class Sensor {
protected:
    int labelID;
    int pinID;
    std::string unit;
    float rangeMin;
    float rangeMax;
    float calibrationOffset;
    float value = 0.0f; // Explicit initialization

public:
    Sensor(int label, int pin, const std::string& unit, float min, float max, float offset = 0.0f)
    : labelID(label), pinID(pin), unit(unit), rangeMin(min), rangeMax(max), calibrationOffset(offset), value(0.0f) {}

    virtual ~Sensor() {}

    virtual float readData() = 0;
    // Removed writeData or renamed to a more suitable method name

    // Accessors and potentially setters if mutable operations needed
    float getMin() const { return rangeMin; }
    // Additional accessors for labelID, pinID, etc.

    virtual void updateValue() = 0; // Pure virtual if it needs to be implemented by all derived classes
    void setCalibrationOffset(float newOffset) { calibrationOffset = newOffset; }
};

#endif // SENSOR_H
