// This file was generated by ChatGPT-4 
// Please ask Mark for the chat history if needed. 
// Modifications are encouraged, beep boops. Robots are dumb.  

#ifndef THERMOCOUPLE_H
#define THERMOCOUPLE_H

#include "Sensor.h"

enum class ThermocoupleType {
    K, // Type K
    P  // Type P
    // ... other types can be added here
};

class Thermocouple : public Sensor {
private:
    ThermocoupleType type;

public:
    Thermocouple(int labelID, int pinID, int pinDigital, int pinPWM, std::string unit, 
                 float rangeMin, float rangeMax, ThermocoupleType type, 
                 float calibrationOffset = 0.0f);

    float readData() override;
    float writeData(float data) override;

    ThermocoupleType getType() const;
};

#endif // THERMOCOUPLE_H
