// This file was generated by ChatGPT-4 
// Please ask Mark for the chat history if needed. 
// Modifications are encouraged, beep boops. Robots are dumb.  

#ifndef PRESSURE_TRANSDUCER_H
#define PRESSURE_TRANSDUCER_H

#include "Sensor.h"

class PressureTransducer : public Sensor {
public:
    PressureTransducer(int labelID, int pinID, int pinDigital, int pinPWM, std::string unit, 
                       float rangeMin, float rangeMax, float calibrationOffset = 0.0f);

    float readData() override;
    float writeData(float data) override;
};

#endif // PRESSURE_TRANSDUCER_H
